SELECT u.USER_ID, 
       u.NICKNAME, 
       CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', u.STREET_ADDRESS2) AS '전체주소', 
       CONCAT(SUBSTRING(u.TLNO, 1, 3), '-', SUBSTRING(u.TLNO, 4, 4), '-', SUBSTRING(u.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER u
JOIN USED_GOODS_BOARD b
ON u.USER_ID = b.WRITER_ID
GROUP BY u.USER_ID
HAVING COUNT(b.BOARD_ID) >= 3
ORDER BY u.USER_ID DESC;