WITH RENTAL_DATE_AND_DURATION_TYPE AS (
SELECT *, CASE 
             WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN NULL
             WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
             WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
             ELSE '90일 이상' 
           END AS R_DURATION_TYPE
        , DATEDIFF(END_DATE, START_DATE) + 1 AS R_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
     JOIN CAR_RENTAL_COMPANY_CAR USING(CAR_ID)
)


SELECT HISTORY_ID, 
       TRUNCATE(R_DATE * DAILY_FEE * (1 - COALESCE(DISCOUNT_RATE, 0)/100), 0) "FEE"
FROM RENTAL_DATE_AND_DURATION_TYPE R 
     LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
        ON R.CAR_TYPE = P.CAR_TYPE AND R.R_DURATION_TYPE = DURATION_TYPE
WHERE R.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC