-- 코드를 입력하세요
WITH sub AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID)
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) desc
    LIMIT 1
)

SELECT p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW r
JOIN MEMBER_PROFILE p
USING(MEMBER_ID)
WHERE MEMBER_ID = (SELECT MEMBER_ID FROM sub)
ORDER BY REVIEW_DATE, REVIEW_TEXT;